# Generated by Django 3.1.4 on 2021-01-24 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=120, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(default='static/avatar1.png', upload_to='profile_pics')),
                ('birthday', models.CharField(blank=True, max_length=30)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('where_do_you_live', models.CharField(blank=True, max_length=100)),
                ('email_when_someone_comment', models.BooleanField(default=False)),
                ('email_when_someone_answer', models.BooleanField(default=False)),
                ('email_when_someone_fallow', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('followers', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
