# Generated by Django 3.1.4 on 2021-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='ide',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
