# Generated by Django 3.1.4 on 2021-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20210121_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='state',
            field=models.CharField(choices=[('Been', 'Been'), ('Wishlist', 'Wishlist'), ('Nope', 'Nope')], default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
